name: KSBMC
version: 0.1.0.0
synopsis: A model checker for the logic of knowledge and safe belief
description: See report.pdf
maintainer: My Name <my.email@example.com>
category: Logic

ghc-options: -Wall

dependencies:
  - QuickCheck
  - base
  - containers
  - directory
  - lens
  - mtl
  - parsec
  - random
  - template-haskell

library:
  source-dirs: lib

executables:
  myprogram:
    main: Main.lhs
    source-dirs: exec
    dependencies:
      - KSBMC

tests:
  simpletests:
    main: simpletests.lhs
    source-dirs: test
    dependencies:
      - KSBMC
      - QuickCheck
      - hspec
